# Generated by Django 5.2.7 on 2025-11-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('viewer', 'View Only'), ('member', 'Member'), ('editor', 'Editor'), ('admin', 'Admin')], max_length=50, unique=True),
        ),
    ]
