# Generated by Django 5.2.7 on 2025-11-02 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuser',
            name='address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='country',
            field=models.CharField(blank=True, choices=[('', ''), ('US', 'United States'), ('CA', 'Canada'), ('MX', 'Mexico'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('IE', 'Ireland'), ('PT', 'Portugal'), ('GR', 'Greece'), ('TR', 'Turkey'), ('JP', 'Japan'), ('CN', 'China'), ('IN', 'India'), ('BR', 'Brazil'), ('AR', 'Argentina'), ('ZA', 'South Africa'), ('EG', 'Egypt'), ('TH', 'Thailand')], max_length=2),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Year is stored but not displayed publicly', null=True),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='member_photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='occupation_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='professional_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='salutation',
            field=models.CharField(blank=True, choices=[('', ''), ('Adm.', 'Adm.'), ('Assoc. Prof.', 'Assoc. Prof.'), ('Capt.', 'Capt.'), ('Col.', 'Col.'), ('Commodore', 'Commodore'), ('Decon', 'Decon'), ('Dr.', 'Dr.'), ('Father', 'Father'), ('Fleet Captain', 'Fleet Captain'), ('Gen.', 'Gen.'), ('Hon.', 'Hon.'), ('Judge', 'Judge'), ('Lady', 'Lady'), ('Maj.', 'Maj.'), ('Mayor', 'Mayor'), ('Miss', 'Miss'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('PC', 'PC'), ('Prof.', 'Prof.'), ('Rabbi', 'Rabbi'), ('Rear Adm.', 'Rear Adm.'), ('Rear Commoder', 'Rear Commoder'), ('Rep.', 'Rep.'), ('Rev.', 'Rev.'), ('Sen.', 'Sen.'), ('Sgt.', 'Sgt.'), ('Teen', 'Teen'), ('Vice-Commodore', 'Vice-Commodore')], max_length=20),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='spouse_first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='spouse_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='state',
            field=models.CharField(blank=True, choices=[('', ''), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='timezone',
            field=models.CharField(blank=True, help_text='e.g., America/New_York', max_length=50),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_beam',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Beam in feet', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_draft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Draft in feet', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_loa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length Overall in feet', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vessel_photos/'),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_power_requirements',
            field=models.CharField(blank=True, choices=[('', ''), ('30a', '30a'), ('50a', '50a'), ('2x30a or 50a', '2x30a or 50a')], max_length=20),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_tie_preferences',
            field=models.CharField(blank=True, choices=[('', ''), ('bow in starboard', 'Bow In Starboard'), ('bow in port', 'Bow In Port'), ('stern in starboard', 'Stern In Starboard'), ('stern in port', 'Stern In Port')], max_length=30),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Motor', 'Motor'), ('Sailboat', 'Sailboat')], max_length=20),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='work_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
