# Generated by Django 5.2.7 on 2025-11-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0004_rename_phone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuser',
            name='vessel_cruising_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average cruising speed in knots', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer/builder of boat', max_length=255),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_model',
            field=models.CharField(blank=True, help_text='Model of boat', max_length=255),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='vessel_moorage_location',
            field=models.CharField(blank=True, help_text='Moorage location', max_length=255),
        ),
    ]
