# Generated by Django 5.2.7 on 2025-11-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0005_add_vessel_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the member type', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this member type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this member type is currently active')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display this member type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member Type',
                'verbose_name_plural': 'Member Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='clubuser',
            name='member_types',
            field=models.ManyToManyField(blank=True, help_text='Member types assigned to this user (at least one required)', related_name='members', to='ManagementApp.membertype'),
        ),
    ]
