# Generated by Django 5.2.8 on 2025-11-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0006_add_member_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuser',
            name='parent_member',
            field=models.ForeignKey(blank=True, help_text='Parent member if this is a dependent/child member', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='relationship_type',
            field=models.CharField(blank=True, help_text='Type of relationship to parent (e.g., "Child", "Spouse", "First Mate")', max_length=50),
        ),
        migrations.AddField(
            model_name='membertype',
            name='can_be_child',
            field=models.BooleanField(default=False, help_text='Members with this type can be children/dependents of parent members'),
        ),
        migrations.AddField(
            model_name='membertype',
            name='can_be_parent',
            field=models.BooleanField(default=False, help_text='Members with this type can be parents of dependent members'),
        ),
        migrations.CreateModel(
            name='MemberTypeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(default='Child', help_text='Name of the relationship (e.g., "Child", "Spouse", "First Mate")', max_length=50)),
                ('max_children', models.IntegerField(blank=True, help_text='Maximum number of children of this type allowed per parent (leave blank for unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this relationship is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_type', models.ForeignKey(help_text='Child/dependent member type', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='ManagementApp.membertype')),
                ('parent_type', models.ForeignKey(help_text='Parent member type', on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='ManagementApp.membertype')),
            ],
            options={
                'verbose_name': 'Member Type Relationship',
                'verbose_name_plural': 'Member Type Relationships',
                'ordering': ['parent_type__display_order', 'child_type__display_order'],
                'unique_together': {('parent_type', 'child_type')},
            },
        ),
    ]
