# Generated by Django 5.2.7 on 2025-11-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0002_eventcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('event_title', models.CharField(help_text='Snapshot of event title at time of action', max_length=200)),
                ('event_data', models.JSONField(blank=True, help_text='Additional event data at time of action (for deleted events)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(blank=True, help_text='Event may be NULL if deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='CalendarApp.event')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Action Log',
                'verbose_name_plural': 'Event Action Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='CalendarApp_timesta_0572a6_idx'), models.Index(fields=['user'], name='CalendarApp_user_id_b1a77b_idx'), models.Index(fields=['action'], name='CalendarApp_action_ad50b0_idx')],
            },
        ),
    ]
