# Generated by Django 5.2.7 on 2025-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0003_eventactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('recommended', 'Recommended'), ('required', 'Required'), ('required_by_close_date', 'Required By Close Date'), ('admins_contacts_only', 'Admins / Event Contacts Only'), ('temporarily_unavailable', 'Temporarily Unavailable'), ('closed', 'Closed'), ('external', 'External')], default='not_required', help_text='Registration status for this event', max_length=30),
        ),
    ]
