# Generated by Django 5.2.7 on 2025-11-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0004_add_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_open_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time when registration opens for this event', null=True),
        ),
    ]
