# Generated by Django 5.2.7 on 2025-11-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0005_add_registration_open_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrant_list_visibility',
            field=models.CharField(choices=[('none', 'None'), ('viewer_public', 'Viewer/Public'), ('members', 'Members'), ('registered_members_only', 'Registered Members Only')], default='none', help_text='Who can view the list of registrants for this event', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open_datetime',
            field=models.DateTimeField(blank=True, help_text='Optional date and time when registration AUTOMATICALLY opens for REGISTRATIONS on this event', null=True),
        ),
    ]
