# Generated by Django 5.2.7 on 2025-11-06 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0006_add_registrant_list_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='When the member registered')),
                ('cancelled', models.BooleanField(default=False, help_text='Whether the registration was cancelled')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the registration was cancelled', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the registration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event being registered for', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='CalendarApp.event')),
                ('member', models.ForeignKey(help_text='Member registering for the event', on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['registered_at'],
                'indexes': [models.Index(fields=['event', 'cancelled'], name='CalendarApp_event_i_46c5c8_idx'), models.Index(fields=['member'], name='CalendarApp_member__4cf1be_idx'), models.Index(fields=['registered_at'], name='CalendarApp_registe_f79118_idx')],
                'unique_together': {('event', 'member')},
            },
        ),
    ]
