# Generated by Django 5.2.8 on 2025-11-11 16:35

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0007_add_event_registration'),
        ('ManagementApp', '0007_clubuser_parent_member_clubuser_relationship_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowed_member_types',
            field=models.ManyToManyField(blank=True, help_text='Member types that can register for this event. Leave empty to allow all types.', related_name='events', to='ManagementApp.membertype'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='additional_members',
            field=models.ManyToManyField(blank=True, help_text='Additional members (dependents) included in this registration', related_name='additional_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total registration fee paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='formatted_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full formatted description with rich text', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(help_text='Primary member registering for the event', on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Guest full name', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Guest email address', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Guest phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event the guest is registered for', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='CalendarApp.event')),
                ('registration', models.ForeignKey(help_text='Registration this guest is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='CalendarApp.eventregistration')),
            ],
            options={
                'verbose_name': 'Event Guest',
                'verbose_name_plural': 'Event Guests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Registration fee amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event this fee applies to', on_delete=django.db.models.deletion.CASCADE, related_name='registration_fees', to='CalendarApp.event')),
                ('member_type', models.ForeignKey(help_text='Member type this fee applies to', on_delete=django.db.models.deletion.CASCADE, related_name='event_fees', to='ManagementApp.membertype')),
            ],
            options={
                'verbose_name': 'Event Registration Fee',
                'verbose_name_plural': 'Event Registration Fees',
                'ordering': ['member_type__display_order', 'member_type__name'],
                'unique_together': {('event', 'member_type')},
            },
        ),
    ]
