# Generated by Django 5.2.8 on 2025-11-11 16:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0007_add_event_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formatted_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full formatted description with rich text', null=True, verbose_name='Text'),
        ),
    ]

