# Generated by Django 5.2.8 on 2025-11-11 16:35
# Modified 11/17/25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0008_upgrade_to_ckeditor5'),
        ('ManagementApp', '0007_clubuser_parent_member_clubuser_relationship_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Handle the allowed_member_types ManyToManyField
        # Use SeparateDatabaseAndState to prevent AddField from trying to create the table if it exists
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Only create table if it doesn't exist
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "CalendarApp_event_allowed_member_types" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "event_id" bigint NOT NULL,
                            "membertype_id" bigint NOT NULL,
                            CONSTRAINT "CalendarApp_event_allowed_member_types_event_id_fkey" 
                                FOREIGN KEY ("event_id") REFERENCES "CalendarApp_event" ("id") 
                                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "CalendarApp_event_allowed_member_types_membertype_id_fkey" 
                                FOREIGN KEY ("membertype_id") REFERENCES "ManagementApp_membertype" ("id") 
                                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "CalendarApp_event_allowed_member_types_event_id_membertype_id_uniq" 
                                UNIQUE ("event_id", "membertype_id")
                        );
                        CREATE INDEX IF NOT EXISTS "CalendarApp_event_allowed_member_types_event_id_idx" 
                            ON "CalendarApp_event_allowed_member_types" ("event_id");
                        CREATE INDEX IF NOT EXISTS "CalendarApp_event_allowed_member_types_membertype_id_idx" 
                            ON "CalendarApp_event_allowed_member_types" ("membertype_id");
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='event',
                    name='allowed_member_types',
                    field=models.ManyToManyField(blank=True, help_text='Member types that can register for this event. Leave empty to allow all types.', related_name='events', to='ManagementApp.membertype'),
                ),
            ]
        ),
        # Handle the additional_members ManyToManyField
        # Use SeparateDatabaseAndState to prevent AddField from trying to create the table if it exists
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Only create table if it doesn't exist
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "CalendarApp_eventregistration_additional_members" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "eventregistration_id" bigint NOT NULL,
                            "clubuser_id" bigint NOT NULL,
                            CONSTRAINT "CalendarApp_eventregistration_additional_members_eventregistration_id_fkey" 
                                FOREIGN KEY ("eventregistration_id") REFERENCES "CalendarApp_eventregistration" ("id") 
                                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "CalendarApp_eventregistration_additional_members_clubuser_id_fkey" 
                                FOREIGN KEY ("clubuser_id") REFERENCES "ManagementApp_clubuser" ("id") 
                                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "CalendarApp_eventregistration_additional_members_eventregistration_id_clubuser_id_uniq" 
                                UNIQUE ("eventregistration_id", "clubuser_id")
                        );
                        CREATE INDEX IF NOT EXISTS "CalendarApp_eventregistration_additional_members_eventregistration_id_idx" 
                            ON "CalendarApp_eventregistration_additional_members" ("eventregistration_id");
                        CREATE INDEX IF NOT EXISTS "CalendarApp_eventregistration_additional_members_clubuser_id_idx" 
                            ON "CalendarApp_eventregistration_additional_members" ("clubuser_id");
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='eventregistration',
                    name='additional_members',
                    field=models.ManyToManyField(blank=True, help_text='Additional members (dependents) included in this registration', related_name='additional_registrations', to=settings.AUTH_USER_MODEL),
                ),
            ]
        ),
        # Handle the total_fee field - add column only if it doesn't exist
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'CalendarApp_eventregistration' 
                                AND column_name = 'total_fee'
                            ) THEN
                                ALTER TABLE "CalendarApp_eventregistration" 
                                ADD COLUMN "total_fee" numeric(10, 2) DEFAULT 0.0 NOT NULL;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='eventregistration',
                    name='total_fee',
                    field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total registration fee paid', max_digits=10),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(help_text='Primary member registering for the event', on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        # Handle EventGuest model - create table only if it doesn't exist
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "CalendarApp_eventguest" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "name" varchar(200) NOT NULL,
                            "email" varchar(254) NOT NULL,
                            "phone_number" varchar(20) NOT NULL,
                            "created_at" timestamp with time zone NOT NULL,
                            "updated_at" timestamp with time zone NOT NULL,
                            "event_id" bigint NOT NULL,
                            "registration_id" bigint NOT NULL,
                            CONSTRAINT "CalendarApp_eventguest_event_id_fkey" 
                                FOREIGN KEY ("event_id") REFERENCES "CalendarApp_event" ("id") 
                                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "CalendarApp_eventguest_registration_id_fkey" 
                                FOREIGN KEY ("registration_id") REFERENCES "CalendarApp_eventregistration" ("id") 
                                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
                        );
                        CREATE INDEX IF NOT EXISTS "CalendarApp_eventguest_event_id_idx" 
                            ON "CalendarApp_eventguest" ("event_id");
                        CREATE INDEX IF NOT EXISTS "CalendarApp_eventguest_registration_id_idx" 
                            ON "CalendarApp_eventguest" ("registration_id");
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='EventGuest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='Guest full name', max_length=200)),
                        ('email', models.EmailField(blank=True, help_text='Guest email address', max_length=254)),
                        ('phone_number', models.CharField(blank=True, help_text='Guest phone number', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('event', models.ForeignKey(help_text='Event the guest is registered for', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='CalendarApp.event')),
                        ('registration', models.ForeignKey(help_text='Registration this guest is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='CalendarApp.eventregistration')),
                    ],
                    options={
                        'verbose_name': 'Event Guest',
                        'verbose_name_plural': 'Event Guests',
                        'ordering': ['name'],
                    },
                ),
            ]
        ),
        # Handle EventRegistrationFee model - create table only if it doesn't exist
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "CalendarApp_eventregistrationfee" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "fee_amount" numeric(10, 2) NOT NULL,
                            "created_at" timestamp with time zone NOT NULL,
                            "updated_at" timestamp with time zone NOT NULL,
                            "event_id" bigint NOT NULL,
                            "member_type_id" bigint NOT NULL,
                            CONSTRAINT "CalendarApp_eventregistrationfee_event_id_fkey" 
                                FOREIGN KEY ("event_id") REFERENCES "CalendarApp_event" ("id") 
                                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "CalendarApp_eventregistrationfee_member_type_id_fkey" 
                                FOREIGN KEY ("member_type_id") REFERENCES "ManagementApp_membertype" ("id") 
                                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "CalendarApp_eventregistrationfee_event_id_member_type_id_uniq" 
                                UNIQUE ("event_id", "member_type_id")
                        );
                        CREATE INDEX IF NOT EXISTS "CalendarApp_eventregistrationfee_event_id_idx" 
                            ON "CalendarApp_eventregistrationfee" ("event_id");
                        CREATE INDEX IF NOT EXISTS "CalendarApp_eventregistrationfee_member_type_id_idx" 
                            ON "CalendarApp_eventregistrationfee" ("member_type_id");
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='EventRegistrationFee',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Registration fee amount', max_digits=10)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('event', models.ForeignKey(help_text='Event this fee applies to', on_delete=django.db.models.deletion.CASCADE, related_name='registration_fees', to='CalendarApp.event')),
                        ('member_type', models.ForeignKey(help_text='Member type this fee applies to', on_delete=django.db.models.deletion.CASCADE, related_name='event_fees', to='ManagementApp.membertype')),
                    ],
                    options={
                        'verbose_name': 'Event Registration Fee',
                        'verbose_name_plural': 'Event Registration Fees',
                        'ordering': ['member_type__display_order', 'member_type__name'],
                        'unique_together': {('event', 'member_type')},
                    },
                ),
            ]
        ),
    ]
