# Generated by Django 5.2.8 on 2025-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0009_event_allowed_member_types_and_more'),
        ('DocumentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='linked_documents',
            field=models.ManyToManyField(blank=True, help_text='Documents from Document Management that are linked to this event', related_name='events', to='DocumentManagement.documentfile'),
        ),
    ]
