# Generated by Django 5.2.8 on 2025-11-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ManagementApp', '0007_clubuser_parent_member_clubuser_relationship_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Folder name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Folder description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder (leave empty for root folder)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='DocumentManagement.documentfolder')),
            ],
            options={
                'verbose_name': 'Document Folder',
                'verbose_name_plural': 'Document Folders',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='File name', max_length=255)),
                ('file', models.FileField(help_text='Upload file', upload_to='documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='File description')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(help_text='Folder containing this file', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DocumentManagement.documentfolder')),
            ],
            options={
                'verbose_name': 'Document File',
                'verbose_name_plural': 'Document Files',
                'ordering': ['name'],
                'unique_together': {('folder', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, help_text='Can view folder and its contents')),
                ('can_add', models.BooleanField(default=False, help_text='Can add files and subfolders')),
                ('can_edit', models.BooleanField(default=False, help_text='Can edit folder and its contents')),
                ('can_delete', models.BooleanField(default=False, help_text='Can delete folder and its contents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(help_text='Folder this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='DocumentManagement.documentfolder')),
                ('role', models.ForeignKey(help_text='Role this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to='ManagementApp.role')),
            ],
            options={
                'verbose_name': 'Folder Permission',
                'verbose_name_plural': 'Folder Permissions',
                'ordering': ['folder', 'role'],
                'unique_together': {('folder', 'role')},
            },
        ),
    ]
