# Generated by Django 5.2.8 on 2025-11-19 18:23

import DocumentManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(help_text='Upload file', upload_to=DocumentManagement.models.get_document_upload_path),
        ),
    ]
